name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode Version
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app' # Replace with your Xcode version

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install --repo-update # If you're using CocoaPods, otherwise remove this step

    - name: Build and Test
      run: |
        xcodebuild -workspace WeatherApp.xcworkspace \
                   -scheme WeatherApp \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
                   build test | xcpretty # Replace with your simulator details and OS version
